import { Activity, ArrowLeft, Bot, CarFront, CloudRain, Gauge, MapPinned, Radio, Sparkles, TrendingUp, TriangleAlert, UsersRound } from 'lucide-react'
import { GlassCard } from './GlassCard'
import { RumboMap } from './RumboMap'
import { money } from './data'

function Metric({ label, value, suffix, accent = 'text-white', icon: Icon }) { return <GlassCard className="p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-medium tracking-[.15em] text-white/40">{label}</p><p className={`mt-4 text-4xl font-semibold tracking-[-.07em] ${accent}`}>{value}<span className="ml-1 text-base tracking-normal text-white/45">{suffix}</span></p></div>{Icon && <Icon size={18} className={accent} />}</div></GlassCard> }

export function CommandCenter({ live, simulation, connected, onTrigger, onStart, onHome }) {
  const metrics = simulation?.metrics || {}
  const baseline = metrics.baseline || {}
  const ai = metrics.ai || {}
  const comparison = metrics.comparison || {}
  const locations = live.orders?.map((order) => ({ id: order.id, client_id: order.client_id, name: order.client_id === 'client_1' ? 'C1 · San Pedro' : 'C2 · Tec' })) || []
  return <main className="rumbo-noise min-h-screen bg-ink"><header className="mx-auto flex max-w-[1550px] items-center justify-between px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><button onClick={onHome} className="rounded-2xl border border-white/10 bg-white/[.06] p-2.5 text-white/70 hover:text-white"><ArrowLeft size={18} /></button><div><p className="text-sm font-semibold">Rumbo | Edge Logistics OS</p><p className="mt-0.5 text-[9px] tracking-[.2em] text-white/40">AI COMMAND CENTER</p></div></div><div className="flex items-center gap-3"><span className={`flex items-center gap-2 text-[10px] tracking-[.15em] ${connected ? 'text-cyan' : 'text-rose-300'}`}><Radio size={13} />{connected ? 'RASPBERRY 10.71.42.73 LIVE' : 'EDGE LINK LOST'}</span><button disabled={!connected || simulation?.running} onClick={onStart} className="app-button-primary">{simulation?.running ? 'Simulación activa' : 'Iniciar demo'}</button></div></header>
    <section className="mx-auto max-w-[1550px] px-5 pb-10 sm:px-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">OPERATING PICTURE · MONTERREY</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.06em] sm:text-5xl">La ventaja se ve en vivo.</h1></div><p className="max-w-sm text-xs leading-5 text-white/45">Baseline y Rumbo AI reciben las mismas condiciones. La diferencia es exclusivamente estratégica.</p></div>
      <div className="grid gap-4 xl:grid-cols-12"><div className="xl:col-span-7"><GlassCard className="relative h-[480px] overflow-hidden p-4"><RumboMap className="h-full" batch={live.batch} locations={locations} /><div className="absolute left-8 top-8 rounded-2xl border border-white/10 bg-black/45 px-4 py-3 backdrop-blur"><p className="eyebrow">LIVE EDGE GRAPH</p><p className="mt-1 text-sm font-medium">{live.batch ? `Batch ${live.batch.id} · ${live.batch.savings_percent}% ahorro` : 'Esperando la primera orden'}</p></div><div className="absolute bottom-7 left-8 right-8 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-rose-400/20 bg-black/45 p-3"><p className="text-[10px] text-white/45">BASELINE</p><p className="mt-1 text-lg font-semibold text-rose-300">{money(baseline.gross_earnings_mxn)}</p></div><div className="rounded-2xl border border-cyan/20 bg-black/45 p-3"><p className="text-[10px] text-white/45">RUMBO AI</p><p className="mt-1 text-lg font-semibold text-cyan">{money(ai.gross_earnings_mxn)}</p></div><div className="rounded-2xl border border-white/10 bg-black/45 p-3"><p className="text-[10px] text-white/45">IA / HORA</p><p className="mt-1 text-lg font-semibold">{ai.mxn_per_hour ?? 0}</p></div><div className="rounded-2xl border border-white/10 bg-black/45 p-3"><p className="text-[10px] text-white/45">MINUTO SIM.</p><p className="mt-1 text-lg font-semibold">{Math.round(simulation?.simulation_minute || 0)}</p></div></div></GlassCard></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:col-span-5"><Metric label="GANANCIAS AI" value={money(ai.gross_earnings_mxn)} accent="text-cyan" icon={TrendingUp} /><Metric label="EFICIENCIA AI" value={ai.mxn_per_km ?? 0} suffix="MXN/km" accent="text-violet-300" icon={Gauge} /><Metric label="MEJORA IA" value={`${((comparison.earnings_improvement || 0) * 100).toFixed(1)}`} suffix="%" accent="text-cyan" icon={Sparkles} /><Metric label="PEDIDOS LIVE" value={live.orders?.length || 0} accent="text-amber-300" icon={UsersRound} /><GlassCard className="sm:col-span-2 p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">DECISIÓN RUMBO EDGE</p><h2 className="mt-2 text-xl font-semibold">{live.batch ? 'Batch recomendado para los dos clientes' : 'Sin batch activo'}</h2></div><Bot className="text-violet" /></div><p className="mt-4 text-sm leading-6 text-white/55">{live.batch?.reasoning || simulation?.last_decisions?.gemini?.reasoning || 'Inicia demo y emite pedidos desde las vistas de cliente.'}</p></GlassCard></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:col-span-12 lg:grid-cols-4"><Metric label="TRÁFICO" value={simulation?.traffic?.congestion_level || 'normal'} accent="text-cyan" icon={CarFront} /><Metric label="CLIMA" value={`${simulation?.weather?.temperature_c ?? 28}°`} accent="text-amber-300" icon={CloudRain} /><Metric label="ORDENES COMPLETADAS" value={ai.orders_completed ?? 0} accent="text-violet-300" icon={Activity} /><Metric label="RETRASOS AI" value={ai.late_orders ?? 0} accent="text-rose-300" icon={TriangleAlert} /></div>
        <GlassCard className="xl:col-span-12 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">SIMULADOR PARA JUECES</p><h2 className="mt-2 text-xl font-semibold">Disrupciones que cambian la ruta</h2></div><div className="flex flex-wrap gap-2"><button onClick={() => onTrigger('TORRENTIAL_RAIN')} className="app-button"><CloudRain size={15} />Lluvia torrencial</button><button onClick={() => onTrigger('GONZALITOS_FLOOD')} className="app-button"><TriangleAlert size={15} />Inundación Gonzalitos</button><button onClick={() => onTrigger('SAN_PEDRO_CONGESTION')} className="app-button"><MapPinned size={15} />Congestionamiento San Pedro</button></div></div></GlassCard>
      </div></section></main>
}
