import { AnimatePresence, motion } from 'framer-motion'
import { BellRing, CheckCircle2, ChefHat, CircleDot, Clock3, MapPin, Navigation, Package, Radio, Route, Sparkles, Truck, X } from 'lucide-react'
import { GlassCard } from './GlassCard'
import { RumboMap } from './RumboMap'

const actions = [
  { id: 'ACCEPT_BATCH', label: 'Aceptar Batch', icon: CheckCircle2, primary: true },
  { id: 'ARRIVED_RESTAURANT', label: 'Llegué a Restaurante', icon: ChefHat },
  { id: 'DELIVERED_CLIENT_1', label: 'Entregado a Cliente 1', icon: Package },
  { id: 'DELIVERED_CLIENT_2', label: 'Entregado a Cliente 2', icon: Package },
]

export function DriverHUD({ live, notification, onDismiss, connected, send, onHome }) {
  const locations = live.orders?.map((order) => ({ id: order.id, client_id: order.client_id, name: order.client_id === 'client_1' ? 'Cliente 1 · San Pedro' : 'Cliente 2 · Tec', coords: order.location })) || []
  const hasBatch = Boolean(live.batch)
  const triggerAction = (action) => send({ type: 'DRIVER_ACTION', action })
  return <main className="rumbo-noise min-h-screen bg-ink"><header className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-5 sm:px-8"><button onClick={onHome} className="flex items-center gap-3 text-left"><span className="rounded-2xl bg-gradient-to-br from-violet to-cyan p-2.5 shadow-glow"><Truck size={19} /></span><span><b className="block text-sm">Rumbo Courier</b><small className="text-[9px] tracking-[.18em] text-white/40">LIVE DELIVERY HUD</small></span></button><div className="flex items-center gap-3"><span className={`flex items-center gap-2 text-[10px] tracking-[.14em] ${connected ? 'text-cyan' : 'text-rose-300'}`}><Radio size={13} />{connected ? 'EDGE LINKED' : 'EDGE OFFLINE'}</span><button onClick={onHome} className="app-button px-3 py-2 text-xs">Salir</button></div></header>
    <section className="mx-auto grid max-w-[1500px] gap-4 px-5 pb-8 sm:px-8 lg:grid-cols-[1.4fr_.6fr]"><div className="relative"><RumboMap className="h-[48vh] min-h-[410px]" batch={live.batch} locations={locations} /><div className="pointer-events-none absolute inset-x-6 top-6 flex items-start justify-between"><div className="glass rounded-2xl px-4 py-3"><p className="eyebrow">RUMBO ROUTE</p><p className="mt-1 text-lg font-semibold">{hasBatch ? 'Batch optimizado activo' : 'Esperando pedidos Edge'}</p></div><div className="glass rounded-2xl px-4 py-3 text-right"><p className="text-[10px] text-white/45">ESTADO</p><p className="mt-1 flex items-center gap-2 text-sm text-cyan"><CircleDot size={14} />{live.batch?.status || 'DISPONIBLE'}</p></div></div><div className="absolute bottom-6 left-6 right-6 grid gap-3 sm:grid-cols-3"><GlassCard className="p-4"><Route className="mb-4 text-cyan" size={18} /><p className="text-2xl font-semibold tracking-tight">{live.batch?.batch_distance_km ?? '—'} km</p><p className="mt-1 text-[10px] text-white/45">Ruta Edge</p></GlassCard><GlassCard className="p-4"><Clock3 className="mb-4 text-violet" size={18} /><p className="text-2xl font-semibold tracking-tight">{hasBatch ? '18' : '—'} min</p><p className="mt-1 text-[10px] text-white/45">ETA estimado</p></GlassCard><GlassCard className="p-4"><Sparkles className="mb-4 text-amber-300" size={18} /><p className="text-2xl font-semibold tracking-tight">{live.batch?.savings_percent ?? '—'}%</p><p className="mt-1 text-[10px] text-white/45">Distancia ahorrada</p></GlassCard></div></div>
      <aside className="space-y-4"><GlassCard className="p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">EDGE SUGGESTION</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.045em]">{hasBatch ? 'Una ruta. Dos destinos.' : 'Tu siguiente entrega aparecerá aquí.'}</h1></div><span className="rounded-2xl bg-violet/20 p-3 text-violet"><Sparkles size={20} /></span></div><p className="mt-5 text-sm leading-6 text-white/55">{live.batch?.reasoning || 'Mantén este HUD abierto. Las solicitudes de los clientes llegan instantáneamente desde la Raspberry Pi.'}</p>{hasBatch && <div className="mt-5 rounded-2xl border border-cyan/20 bg-cyan/10 p-4 text-xs text-cyan">Pickup: Rumbo Kitchen · Centrito Valle<br />Secuencia: {locations.map((item) => item.name).join(' → ')}</div>}</GlassCard><GlassCard className="p-4"><p className="mb-3 px-2 text-[10px] font-medium tracking-[.16em] text-white/40">ACCIONES EN VIVO</p><div className="grid gap-2">{actions.map(({ id, label, icon: Icon, primary }) => <button key={id} disabled={!connected || !hasBatch} onClick={() => triggerAction(id)} className={primary ? 'app-button-primary py-3' : 'app-button py-3'}><Icon size={16} />{label}</button>)}</div></GlassCard><GlassCard className="p-5"><div className="flex items-center gap-3"><MapPin className="text-cyan" size={18} /><div><p className="text-sm font-medium">Monterrey Live Mesh</p><p className="mt-1 text-xs text-white/45">La recomendación se recalcula cuando los jueces activan disrupciones.</p></div></div></GlassCard></aside></section>
    <AnimatePresence>{notification && <motion.div initial={{ opacity: 0, scale: .92, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .94, y: 16 }} className="fixed inset-0 z-30 flex items-center justify-center bg-black/60 p-5 backdrop-blur-md"><motion.div animate={{ boxShadow: ['0 0 0 rgba(6,182,212,0)', '0 0 70px rgba(6,182,212,.35)', '0 0 0 rgba(6,182,212,0)'] }} transition={{ repeat: 2, duration: .75 }} className="relative w-full max-w-md rounded-[2rem] border border-cyan/40 bg-[#101522]/90 p-7 backdrop-blur-2xl"><button onClick={onDismiss} className="absolute right-5 top-5 text-white/45 hover:text-white"><X size={18} /></button><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan/20 text-cyan"><BellRing size={27} /></div><p className="eyebrow">NUEVA MISIÓN EDGE</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{notification.title}</h2><p className="mt-4 text-sm leading-6 text-white/60">{notification.batch?.reasoning}</p><button onClick={onDismiss} className="app-button-primary mt-6 w-full">Ver ruta optimizada</button></motion.div></motion.div>}</AnimatePresence>
  </main>
}
